<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search usuario
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["usuario/new", "Create usuario"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "usuario/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodUsuario" class="col-sm-2 control-label">Cod Of Usuario</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Cod_usuario", "type" => "number", "class" => "form-control", "id" => "fieldCodUsuario"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLoginUsuario" class="col-sm-2 control-label">Login Of Usuario</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Login_usuario", "size" => 30, "class" => "form-control", "id" => "fieldLoginUsuario"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSenhaUsuario" class="col-sm-2 control-label">Senha Of Usuario</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Senha_usuario", "size" => 30, "class" => "form-control", "id" => "fieldSenhaUsuario"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNomeUsuario" class="col-sm-2 control-label">Nome Of Usuario</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Nome_usuario", "size" => 30, "class" => "form-control", "id" => "fieldNomeUsuario"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdadeUsuario" class="col-sm-2 control-label">Idade Of Usuario</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Idade_usuario", "type" => "number", "class" => "form-control", "id" => "fieldIdadeUsuario"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEnderecoUsuario" class="col-sm-2 control-label">Endereco Of Usuario</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Endereco_usuario", "size" => 30, "class" => "form-control", "id" => "fieldEnderecoUsuario"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCidadecodCidade" class="col-sm-2 control-label">CIDADECod Of Cidade</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["CIDADECod_cidade", "type" => "number", "class" => "form-control", "id" => "fieldCidadecodCidade"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTipoUsuariocodTipoUsuario" class="col-sm-2 control-label">TIPO Of USUARIOCod Of Tipo Of Usuario</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["TIPO_USUARIOCod_tipo_usuario", "type" => "number", "class" => "form-control", "id" => "fieldTipoUsuariocodTipoUsuario"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
