<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["usuario/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["usuario/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Cod Of Usuario</th>
            <th>Login Of Usuario</th>
            <th>Senha Of Usuario</th>
            <th>Nome Of Usuario</th>
            <th>Idade Of Usuario</th>
            <th>Endereco Of Usuario</th>
            <th>CIDADECod Of Cidade</th>
            <th>TIPO Of USUARIOCod Of Tipo Of Usuario</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $usuario): ?>
            <tr>
                <td><?php echo $usuario->Cod_usuario ?></td>
            <td><?php echo $usuario->Login_usuario ?></td>
            <td><?php echo $usuario->Senha_usuario ?></td>
            <td><?php echo $usuario->Nome_usuario ?></td>
            <td><?php echo $usuario->Idade_usuario ?></td>
            <td><?php echo $usuario->Endereco_usuario ?></td>
            <td><?php echo $usuario->CIDADECod_cidade ?></td>
            <td><?php echo $usuario->TIPO_USUARIOCod_tipo_usuario ?></td>

                <td><?php echo $this->tag->linkTo(["usuario/edit/" . $usuario->Cod_usuario, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["usuario/delete/" . $usuario->Cod_usuario, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("usuario/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
