<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search cidade
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["cidade/new", "Create cidade"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "cidade/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodCidade" class="col-sm-2 control-label">Cod Of Cidade</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Cod_cidade", "type" => "number", "class" => "form-control", "id" => "fieldCodCidade"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCidade" class="col-sm-2 control-label">Cidade</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Cidade", "size" => 30, "class" => "form-control", "id" => "fieldCidade"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUfCidade" class="col-sm-2 control-label">UF Of Cidade</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["UF_cidade", "size" => 30, "class" => "form-control", "id" => "fieldUfCidade"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
