<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search aula
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["aula/new", "Create aula"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "aula/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodAula" class="col-sm-2 control-label">Cod Of Aula</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Cod_aula", "type" => "number", "class" => "form-control", "id" => "fieldCodAula"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldConteudoAula" class="col-sm-2 control-label">Conteudo Of Aula</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["Conteudo_aula", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldConteudoAula"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldClassecodClasse" class="col-sm-2 control-label">CLASSECod Of Classe</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["CLASSECod_Classe", "type" => "number", "class" => "form-control", "id" => "fieldClassecodClasse"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
